### ISSUE TITLE
extraneous files in repository

### ISSUE THREAD

**Issue by vnmanoharan** [p201-sp2016/params_MOT#19]
You should delete the extraneous files and add them to .gitignore.  That way you can regenerate them in your local tree, but they won't clutter the repository. Extraneous files:
- .ipynb_checkpoints
- dist (and subdirectories)
- *.egg-info
- .spyderworkspace
- `__pycache__` directories

**Comment by vnmanoharan** [comment]
These files are still showing up, which is making it difficult to do a fetch/pull operation (they get updated everytime the code is executed).

**Comment by vnmanoharan** [comment]
Please fix this.

**Comment by AndreiHG** [comment]
I think they should be gone now.
