### ISSUE TITLE
model issues

### ISSUE THREAD

**Issue by vnmanoharan** [p201-sp2016/params_MOT#22]
A few issues with the model:

- you'll have to work with the convolved Gaussian-Poisson for your likelihood. Remember, adding the poisson noise to the model image just adds a particular realization of the noise. The likelihood function, however, should estimate the probability of the data relative to *all* realizations of the noise.  That is why you end up with a convolution.

- I think it would be fine to start by assuming the Gaussian approximation to a Poisson distribution.  It is probably not accurate for your experiment, but you can easily convolve the Gaussians. Later you can deal with the mixed Gaussian-Poisson case.

- I don't quite understand how you are including the readout "blooming" in your likelihood function. I thought you would just do the sum over pixels in your generative model, then calculate a likelihood function based on the random uncertainties. We should discuss.

**Comment by AndreiHG** [comment]
For now, we will simply assume the noise is Gaussian, and consider the Poisson-Gaussian interpolation case later.

For the readout part, as discussed, we will include it as a deterministic effect in the generative model itself. This should make the calculation of the likelihood more tractable.
