### ISSUE TITLE
can't load simulated data in model.ipynb

### ISSUE THREAD

**Issue by vnmanoharan** [p201-sp2016/params_MOT#41]
I get the error below.   I think this is a problem with `get_data_file_path()`.  You need to use the code in that function that discusses what to do if your data is located in a directory a level above your package directory.  Remember that model.ipynb is run in the root directory, so it saves the simulated data in that directory.

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-107c64217738> in <module>()
      1 model_data_path = get_data_file_path('model_data.csv')
----> 2 model_data = load_data(data_file = model_data_path, delim = ' ')
      3 
      4 image_size = 50
      5 

C:\Users\vnm\Documents\GitHub\p201\params_MOT\params_MOT\io_package.py in load_data(data_file, delim)
     18 
     19 def load_data(data_file, delim = ' '):
---> 20     return loadtxt(data_file, delimiter = delim)
     21 
     22 def load_image(data, image_size = 50):

C:\Users\vnm\Anaconda3\lib\site-packages\numpy\lib\npyio.py in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin)
    803                 fh = iter(open(fname, 'U'))
    804             else:
--> 805                 fh = iter(open(fname))
    806         else:
    807             fh = iter(fname)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\vnm\\Documents\\GitHub\\p201\\params_MOT\\params_MOT\\model_data.csv'

**Comment by bengarber** [comment]
(Peer review)

I had this same issue, and jury-rigged it to work for further testing by telling it to find the full path for "../model_data.csv"--however, this is not meant to be a permanent solution for you.

**Comment by dga471** [comment]
Fixed in latest version of iopackage.py.
