### ISSUE TITLE
MCMC traces look strange

### ISSUE THREAD

**Issue by vnmanoharan** [p201-sp2016/params_MOT#42]
model.ipynb shows some strange looking MCMC traces.  It looks like your walkers haven't equilibrated, and some of them are getting stuck.  It can be helpful to first find the MAP (using an optimization algorithm like Levenberg-Marquardt) and then distribute your walkers around the MAP.  That will help them equilibrate more rapidly, assuming the posterior is monomodal.

If that doesn't work, you'll have to try parallel tempering or HMC (using pymc3).

**Comment by loic-a** [comment]
Hi Vinny.
We are still unable to make the MCMC work. We have now simplified everything to fitting only the widths of the gaussian and inserting manually all of the other values. The output is a strongly bimodal distribution for reason we do not understand. You can manually look at the output of the likelihood functions, and it is minimized at the actual value of the model data, so it appears to be the MCMC which doesn't work for some reason.

There is a new branch called MCMC-test-branch where you can run this simplified model_MOT.ipynb and check the parameters in __init__.py to see if there is anything obviously wrong.
Thanks

**Comment by vnmanoharan** [comment]
OK, will look at it soon.

**Comment by loic-a** [comment]
Hi Vinny,

Was there anything obviously wrong in the code?

**Comment by vnmanoharan** [comment]
I'm still testing it.  I haven't found anything yet. The reason for the bimodal distribution is that the walkers are always going to the boundaries of the prior.  Still trying to figure out why this is happening.

**Comment by vnmanoharan** [comment]
So here is one problem: you are missing the statement 
`x, y = np.meshgrid(x, y)`
in your `sampler()` function. Without that line your model doesn't produce a 2D data set.  

Fixing this prevents the walkers from going to the boundaries and gives reasonable results, but there are still some issues with the traces.

**Comment by loic-a** [comment]
Thanks! That seems to have fixed everything.

**Comment by vnmanoharan** [comment]
yes, sorry.  I said there were some issues with the traces, but actually everything looks good now.  You should see that with this fix, the walkers will zero in on the exact value of sigma_x and sigma_y.
