### ISSUE TITLE
Unclear name of repo

### ISSUE THREAD

**Issue by bengarber** [p201-sp2016/params_MOT#44]
(peer review)

I really like your description of what the repo does--I think that it's clear and gives me an idea of what your code is supposed to do.  However, I don't think that the title of the repository helps--from the description, it seems like what the package does is find MOT cloud size (much more specific than "MOT parameters").

It's also possible that you'll want to point out either in the name or the description that what your project actually does is look for a 2D Gaussian in image (or image-like) data in presence of shot and dark noise.

**Comment by dga471** [comment]
Updated README.md with fuller description of what the package does at the moment. We will continue to update this as we keep developing it. As for the name itself, we might change it at the very end after we know the final scope of the package that we achieve during the course of the project. For right now a lot of code is under development assuming that the package name is "params_MOT".
