### ISSUE TITLE
Don't quite get why there are two model files

### ISSUE THREAD

**Issue by bengarber** [p201-sp2016/params_MOT#45]
__If I'm understanding right (model_MOTonly.ipynb is pretty minimal, and if it's permanent please comment more), model_MOTonly.ipynb is a legacy version that mostly shows how the model works.  If that's the case, after this week please condense what you think are the key takeaways into the other model file.  It also has two small bugs (a line that just says "in" in the preamble, as well as this error in the final image):__
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-11-3a9441554e01> in <module>()
      6 
      7 plt.figure(2)
----> 8 plt.imshow(filters.gaussian_filter(image,2),cmap="jet", interpolation='none' )
      9 plt.colorbar()

NameError: name 'filters' is not defined

**Comment by dga471** [comment]
All of the relevant content of model_MOTonly,ipynb has already been transferred to model.ipynb, and we were indeed planning to delete it in the next commit.
