### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by ralex0** [p201-sp2016/params_MOT#49]
The project needs docstrings. The [numpy/scipy](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#sections) guide is a pretty good template to follow.

**Comment by ralex0** [comment]
By the way, when you update MOT_image.py, since the function MOTmodel is just an alias for gaussian_2d you can just write `MOTmodel = gaussian_2d` for its definition. Or just delete one of them if you don't really need both names).

**Comment by dga471** [comment]
Added docstrings to each function of __init__.py. Also deleted MOT_model function and replaced it with a variable appropriately in the functions which call it.
